name_1 = input("Enter a name: ")
name_2 = input("Now, enter another name: ")
name_3 = input("And now another name: ")
name_4 = input("Finally, one last name: ")
mat_1 = input("Now, enter the name of a weak building material: ")
mat_2 = input("Now the name of a stronger building material: ")
mat_3 = input("Finally, enter the name of a very strong building material: ")

print("There were once three little pigs")
print("The first one was called " + name_1)
print("The second was called " + name_2)
print("And the third was called " + name_3)
print("They each made houses out of different materials")
print("The first piggy used " + mat_1)
print("The second piggy used " + mat_2)
print("And the last piggy used " + mat_3)
print("But there was a big, bad wolf called " + name_4)
print("He tried to blow down all of the houses, but couldn't blow the last one made of " + mat_3)
print("After that, all the piggies lived in their third house happily ever after")